FC = gfortran
FCOPTS = -O3
LN = $(FC)
LNOPTS =

# Object files
OBJS = linalg.o supercell.o test.o

test: $(OBJS)
	$(LN) $(LNOPTS) -o test $(OBJS)
linalg.o: linalg.f90
	$(FC) $(FCOPTS) -c linalg.f90
supercell.o: supercell.f90
	$(FC) $(FCOPTS) -c supercell.f90
	#$(FC) -shared -fPIC -c supercell.f90 -o libsupercell.so -fPIC
test.o: test.f90
	$(FC) $(FCOPTS) -c test.f90

clean:
	rm -f *.o *.so *.mod


